<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test_RSTK_1/tests" tests="1" failures="1" skipped="0" hostname="LAPTOP-BJ5N0QR9" time="18.495" timestamp="Mon Feb 01 10:01:25 IST 2021">
	<properties>
		<property name="excludeCallableTestCases" value="true"/>
		<property name="testEnvironment" value=""/>
		<property name="pluginOutputLevel" value="WARNING"/>
		<property name="projectPath" value=".."/>
		<property name="salesforceMetadataCache" value="Reuse"/>
		<property name="resultsPathDisposition" value="Increment"/>
		<property name="testOutputLevel" value="INFO"/>
		<property name="webBrowserType" value="Chrome"/>
		<property name="resultsPath" value="../ANT/Results"/>
		<property name="webBrowserConfiguration" value="1024x768"/>
		<property name="projectCachePath" value="F:\Automation\ProvarRepository_Test_RSTK1\Test_RSTK_1\ANT\..\..\.provarCaches"/>
	</properties>
	<testcase classname="tests/Sales Order VF.testcase" name="Sales Order VF.testcase" time="18.495">
		<failure message="Execution failed"><![CDATA[Connection exception while opening Partner connection.  Connection name: Devqaff, environment: <default>, authEndpoint: https://login.salesforce.com/services/Soap/u/50.0, userName: achoudhary@rootstock.com.dev-qa-ff, password: [supplied], securityToken: [supplied], messages: [ConnectionException: Failed to send request to https://login.salesforce.com/services/Soap/u/50.0, UnknownHostException: login.salesforce.com]]]></failure>
	</testcase>
</testsuite>
